# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param user_id: The user_id of this InlineResponse2001.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'user_id': str
        }

        self.attribute_map = {
            'user_id': 'user_id'
        }
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this InlineResponse2001.

        User's ID which will be used for user identification in future requests  # noqa: E501

        :return: The user_id of this InlineResponse2001.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this InlineResponse2001.

        User's ID which will be used for user identification in future requests  # noqa: E501

        :param user_id: The user_id of this InlineResponse2001.
        :type user_id: str
        """

        self._user_id = user_id
