# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ManagerRegisterUserBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, phone_number: str=None, subscription_duration_days: int=None):  # noqa: E501
        """ManagerRegisterUserBody - a model defined in Swagger

        :param name: The name of this ManagerRegisterUserBody.  # noqa: E501
        :type name: str
        :param phone_number: The phone_number of this ManagerRegisterUserBody.  # noqa: E501
        :type phone_number: str
        :param subscription_duration_days: The subscription_duration_days of this ManagerRegisterUserBody.  # noqa: E501
        :type subscription_duration_days: int
        """
        self.swagger_types = {
            'name': str,
            'phone_number': str,
            'subscription_duration_days': int
        }

        self.attribute_map = {
            'name': 'name',
            'phone_number': 'phone_number',
            'subscription_duration_days': 'subscription_duration_days'
        }
        self._name = name
        self._phone_number = phone_number
        self._subscription_duration_days = subscription_duration_days

    @classmethod
    def from_dict(cls, dikt) -> 'ManagerRegisterUserBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The manager_register_user_body of this ManagerRegisterUserBody.  # noqa: E501
        :rtype: ManagerRegisterUserBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ManagerRegisterUserBody.

        Gym member's name  # noqa: E501

        :return: The name of this ManagerRegisterUserBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ManagerRegisterUserBody.

        Gym member's name  # noqa: E501

        :param name: The name of this ManagerRegisterUserBody.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this ManagerRegisterUserBody.

        Gym member's phone number  # noqa: E501

        :return: The phone_number of this ManagerRegisterUserBody.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this ManagerRegisterUserBody.

        Gym member's phone number  # noqa: E501

        :param phone_number: The phone_number of this ManagerRegisterUserBody.
        :type phone_number: str
        """
        if phone_number is None:
            raise ValueError("Invalid value for `phone_number`, must not be `None`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def subscription_duration_days(self) -> int:
        """Gets the subscription_duration_days of this ManagerRegisterUserBody.

        Продолжительность абонимента в днях  # noqa: E501

        :return: The subscription_duration_days of this ManagerRegisterUserBody.
        :rtype: int
        """
        return self._subscription_duration_days

    @subscription_duration_days.setter
    def subscription_duration_days(self, subscription_duration_days: int):
        """Sets the subscription_duration_days of this ManagerRegisterUserBody.

        Продолжительность абонимента в днях  # noqa: E501

        :param subscription_duration_days: The subscription_duration_days of this ManagerRegisterUserBody.
        :type subscription_duration_days: int
        """
        if subscription_duration_days is None:
            raise ValueError("Invalid value for `subscription_duration_days`, must not be `None`")  # noqa: E501

        self._subscription_duration_days = subscription_duration_days
