# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, avg_attend_times: float=None, avg_session_duration_hours: float=None, attendance_stats_by_day: List[object]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param avg_attend_times: The avg_attend_times of this InlineResponse200.  # noqa: E501
        :type avg_attend_times: float
        :param avg_session_duration_hours: The avg_session_duration_hours of this InlineResponse200.  # noqa: E501
        :type avg_session_duration_hours: float
        :param attendance_stats_by_day: The attendance_stats_by_day of this InlineResponse200.  # noqa: E501
        :type attendance_stats_by_day: List[object]
        """
        self.swagger_types = {
            'avg_attend_times': float,
            'avg_session_duration_hours': float,
            'attendance_stats_by_day': List[object]
        }

        self.attribute_map = {
            'avg_attend_times': 'avg_attend_times',
            'avg_session_duration_hours': 'avg_session_duration_hours',
            'attendance_stats_by_day': 'attendance_stats_by_day'
        }
        self._avg_attend_times = avg_attend_times
        self._avg_session_duration_hours = avg_session_duration_hours
        self._attendance_stats_by_day = attendance_stats_by_day

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def avg_attend_times(self) -> float:
        """Gets the avg_attend_times of this InlineResponse200.

        Average attendance times  # noqa: E501

        :return: The avg_attend_times of this InlineResponse200.
        :rtype: float
        """
        return self._avg_attend_times

    @avg_attend_times.setter
    def avg_attend_times(self, avg_attend_times: float):
        """Sets the avg_attend_times of this InlineResponse200.

        Average attendance times  # noqa: E501

        :param avg_attend_times: The avg_attend_times of this InlineResponse200.
        :type avg_attend_times: float
        """

        self._avg_attend_times = avg_attend_times

    @property
    def avg_session_duration_hours(self) -> float:
        """Gets the avg_session_duration_hours of this InlineResponse200.

        Average gym's session duration  # noqa: E501

        :return: The avg_session_duration_hours of this InlineResponse200.
        :rtype: float
        """
        return self._avg_session_duration_hours

    @avg_session_duration_hours.setter
    def avg_session_duration_hours(self, avg_session_duration_hours: float):
        """Sets the avg_session_duration_hours of this InlineResponse200.

        Average gym's session duration  # noqa: E501

        :param avg_session_duration_hours: The avg_session_duration_hours of this InlineResponse200.
        :type avg_session_duration_hours: float
        """

        self._avg_session_duration_hours = avg_session_duration_hours

    @property
    def attendance_stats_by_day(self) -> List[object]:
        """Gets the attendance_stats_by_day of this InlineResponse200.

        User's stocks in possession  # noqa: E501

        :return: The attendance_stats_by_day of this InlineResponse200.
        :rtype: List[object]
        """
        return self._attendance_stats_by_day

    @attendance_stats_by_day.setter
    def attendance_stats_by_day(self, attendance_stats_by_day: List[object]):
        """Sets the attendance_stats_by_day of this InlineResponse200.

        User's stocks in possession  # noqa: E501

        :param attendance_stats_by_day: The attendance_stats_by_day of this InlineResponse200.
        :type attendance_stats_by_day: List[object]
        """

        self._attendance_stats_by_day = attendance_stats_by_day
