openapi: 3.0.1
info:
  title: Stats API
  description: API for gym statistics
  version: 1.0.0
servers:
- url: /
tags:
- name: stats
  description: Handles for accessing gym usage statistics
paths:
  /stats/get_total_gym_attendance_stats:
    get:
      tags:
      - stats
      summary: Get gym's attendance stats
      operationId: stats_get_total_gym_attendance_stats_get
      responses:
        "200":
          description: Gym's attendance statistics
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-openapi-router-controller: swagger_server.controllers.stats_controller
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        avg_attend_times:
          type: number
          description: Average attendance times
        avg_session_duration_hours:
          type: number
          description: Average gym's session duration
        attendance_stats_by_day:
          type: array
          description: User's stocks in possession
          items:
            type: object
            additionalProperties: false
      additionalProperties: false
      example:
        avg_attend_times: 0.8008281904610115
        avg_session_duration_hours: 6.027456183070403
        attendance_stats_by_day:
        - {}
        - {}
x-original-swagger-version: "2.0"

