# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse403(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, subscription_ended_at: datetime=None):  # noqa: E501
        """InlineResponse403 - a model defined in Swagger

        :param subscription_ended_at: The subscription_ended_at of this InlineResponse403.  # noqa: E501
        :type subscription_ended_at: datetime
        """
        self.swagger_types = {
            'subscription_ended_at': datetime
        }

        self.attribute_map = {
            'subscription_ended_at': 'subscription_ended_at'
        }
        self._subscription_ended_at = subscription_ended_at

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse403':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_403 of this InlineResponse403.  # noqa: E501
        :rtype: InlineResponse403
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_ended_at(self) -> datetime:
        """Gets the subscription_ended_at of this InlineResponse403.

        Last active subscription ended at  # noqa: E501

        :return: The subscription_ended_at of this InlineResponse403.
        :rtype: datetime
        """
        return self._subscription_ended_at

    @subscription_ended_at.setter
    def subscription_ended_at(self, subscription_ended_at: datetime):
        """Sets the subscription_ended_at of this InlineResponse403.

        Last active subscription ended at  # noqa: E501

        :param subscription_ended_at: The subscription_ended_at of this InlineResponse403.
        :type subscription_ended_at: datetime
        """
        if subscription_ended_at is None:
            raise ValueError("Invalid value for `subscription_ended_at`, must not be `None`")  # noqa: E501

        self._subscription_ended_at = subscription_ended_at
