# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, exit_at: datetime=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param exit_at: The exit_at of this InlineResponse2001.  # noqa: E501
        :type exit_at: datetime
        """
        self.swagger_types = {
            'exit_at': datetime
        }

        self.attribute_map = {
            'exit_at': 'exit_at'
        }
        self._exit_at = exit_at

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def exit_at(self) -> datetime:
        """Gets the exit_at of this InlineResponse2001.

        Time of user's gym exit  # noqa: E501

        :return: The exit_at of this InlineResponse2001.
        :rtype: datetime
        """
        return self._exit_at

    @exit_at.setter
    def exit_at(self, exit_at: datetime):
        """Sets the exit_at of this InlineResponse2001.

        Time of user's gym exit  # noqa: E501

        :param exit_at: The exit_at of this InlineResponse2001.
        :type exit_at: datetime
        """
        if exit_at is None:
            raise ValueError("Invalid value for `exit_at`, must not be `None`")  # noqa: E501

        self._exit_at = exit_at
